import "./globals.css";
import type { Metadata } from "next";
import Providers from "./provider";
import StyledComponentsRegistry from "./_lib/network/registry";
import { Inter, Poor_Story, Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const interScript = Inter({
  variable: "--inter-script-font",
  weight: "400",
  preload: false,
});

const poorStoryScript = Poor_Story({
  variable: "--poor-story-font",
  weight: "400",
  preload: false,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={`${interScript.variable} ${poorStoryScript.variable}`}>
      <body>
        <StyledComponentsRegistry>
          <Providers>{children}</Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
